# Generated by Django 5.1.4 on 2025-01-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_rename_uploader_video_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image_file',
            field=models.FileField(default='youtube/assets/default.png', upload_to='images/'),
        ),
    ]
