# Generated by Django 5.1.4 on 2025-01-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_video_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image_file',
            field=models.FileField(default='images/default.png', upload_to='images/'),
        ),
    ]
