# Generated by Django 5.1.4 on 2025-01-09 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_alter_video_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image_file',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('issue_minute', models.FloatField()),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.video')),
            ],
        ),
    ]
