# Generated by Django 5.1.4 on 2025-01-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
    ]
