# Generated by Django 5.1.4 on 2025-01-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0011_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='like_counter',
            field=models.IntegerField(default=0),
        ),
    ]
