# Generated by Django 5.1.4 on 2025-01-13 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0012_video_like_counter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
