# Generated by Django 5.1.4 on 2025-01-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0016_alter_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('none', 'None'), ('male', 'Male'), ('female', 'Female')], default='none', max_length=10),
        ),
    ]
