# Generated by Django 5.1.4 on 2025-01-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0020_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('game', 'Game'), ('entertainment', 'Entertainment'), ('music', 'Music'), ('shows', 'Shows'), ('other', 'Other')], default='none', max_length=30),
        ),
    ]
