# Generated by Django 5.1.4 on 2025-01-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0021_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('other', 'Other'), ('game', 'Game'), ('entertainment', 'Entertainment'), ('music', 'Music'), ('shows', 'Shows'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
