# Generated by Django 5.1.4 on 2025-02-14 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0024_alter_video_category_watchhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchhistory',
            options={'ordering': ['-watched_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='youtube.comment'),
        ),
    ]
