# Generated by Django 5.1.4 on 2025-02-15 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0025_alter_watchhistory_options_comment_parent_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(choices=[(1, '★☆☆☆☆ 1 Star'), (2, '★★☆☆☆ 2 Stars'), (3, '★★★☆☆ 3 Stars'), (4, '★★★★☆ 4 Stars'), (5, '★★★★★ 5 Stars')], default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
