# Generated by Django 5.1.4 on 2025-02-17 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0026_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReedemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses', models.IntegerField(default=0)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reedemer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
