# Generated by Django 5.1.4 on 2025-02-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0027_reedemcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='reedemcode',
            name='code',
            field=models.CharField(default='', max_length=32),
        ),
    ]
