# Generated by Django 5.1.4 on 2025-02-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0029_redeemcode_delete_reedemcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redeemcode',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='redeemcode',
            name='used_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
