# Generated by Django 5.1.4 on 2025-02-17 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0030_remove_redeemcode_user_user_premium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redeemcode',
            name='used_at',
        ),
        migrations.CreateModel(
            name='ReedemCodeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.redeemcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
