# Generated by Django 5.1.4 on 2025-02-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0036_alter_playlist_parent_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='videosNumber',
            field=models.IntegerField(default=0),
        ),
    ]
