# Generated by Django 5.1.4 on 2025-02-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0037_playlist_videosnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='videosNumber',
            field=models.IntegerField(default=1),
        ),
    ]
