# Generated by Django 5.1.4 on 2025-02-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0038_alter_playlist_videosnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
