# Generated by Django 5.1.4 on 2025-02-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0039_alter_playlist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
