# Generated by Django 5.1.4 on 2025-02-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0040_alter_playlist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=20),
        ),
    ]
