# Generated by Django 5.1.4 on 2025-02-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0041_playlist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isPinned',
            field=models.BooleanField(default=False),
        ),
    ]
