# Generated by Django 5.1.4 on 2025-02-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0042_comment_ispinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hasPinned',
            field=models.BooleanField(default=False),
        ),
    ]
